apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TYPE role_type AS ENUM (
      'administrator', 'researcher', 'respondent'
    );
  
    CREATE TYPE age_type AS ENUM (
      'young', 'adult', 'elderly'
    );
    
    CREATE TYPE gender_type AS ENUM (
      'cis-woman', 'trans-woman', 'cis-man', 'trans-man', 'non-binary'
    );
  
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      code VARCHAR(16) NOT NULL,
      age age_type,
      gender gender_type,
      role role_type,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS surveys (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      status TEXT,
      user_id INTEGER NOT NULL REFERENCES users(id),
      public_id TEXT UNIQUE
    );

    CREATE TABLE IF NOT EXISTS questions (
      id SERIAL PRIMARY KEY,
      survey_id INTEGER NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
      text TEXT NOT NULL,
      type TEXT NOT NULL CHECK (type IN ('single', 'multiple'))
    );

    CREATE TABLE IF NOT EXISTS items (
      id SERIAL PRIMARY KEY,
      question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
      text TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS responses (
      id SERIAL PRIMARY KEY,
      survey_id INTEGER REFERENCES surveys(id)
      age TEXT,
      gender TEXT,
      answers JSONB
    );

    -- MAX 3 QUESTIONS
    CREATE OR REPLACE FUNCTION check_max_questions()
    RETURNS TRIGGER AS $$
    BEGIN
      IF (
        SELECT COUNT(*) FROM questions WHERE survey_id = NEW.survey_id
      ) >= 3 THEN
        RAISE EXCEPTION 'Uma pesquisa não pode ter mais que 3 perguntas';
      END IF;

      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_max_questions
    BEFORE INSERT ON questions
    FOR EACH ROW
    EXECUTE FUNCTION check_max_questions();

    -- MAX 5 ITEMS
    CREATE OR REPLACE FUNCTION check_items_limit()
    RETURNS TRIGGER AS $$
    DECLARE
      total INTEGER;
    BEGIN
      SELECT COUNT(*) INTO total
      FROM items
      WHERE question_id = NEW.question_id;

      IF total >= 5 THEN
        RAISE EXCEPTION 'Máximo de 5 opções por pergunta';
      END IF;

      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_max_items
    BEFORE INSERT ON items
    FOR EACH ROW
    EXECUTE FUNCTION check_items_limit();

    -- MIN 2 ITEMS (validação manual)
    CREATE OR REPLACE FUNCTION validate_min_items(q_id INTEGER)
    RETURNS BOOLEAN AS $$
    DECLARE
      total INTEGER;
    BEGIN
      SELECT COUNT(*) INTO total FROM items WHERE question_id = q_id;

      IF total < 2 THEN
        RAISE EXCEPTION 'Pergunta deve ter pelo menos 2 opções';
      END IF;

      RETURN TRUE;
    END;
    $$ LANGUAGE plpgsql;

    -- ROLE + ACTIVE CHECK
    CREATE OR REPLACE FUNCTION check_user_role_for_survey()
    RETURNS TRIGGER AS $$
    DECLARE
      user_role INTEGER;
      user_active BOOLEAN;
    BEGIN
      SELECT role, active INTO user_role, user_active
      FROM users
      WHERE id = NEW.user_id;

      IF user_active IS NOT TRUE THEN
        RAISE EXCEPTION 'Usuário inativo não pode criar pesquisa';
      END IF;

      IF user_role NOT IN ('administrator', 'researcher') THEN
        RAISE EXCEPTION 'Usuário não autorizado (role deve ser administrator ou researcher)';
      END IF;

      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER trg_check_user_role
    BEFORE INSERT ON surveys
    FOR EACH ROW
    EXECUTE FUNCTION check_user_role_for_survey();

    CREATE INDEX idx_questions_survey ON questions(survey_id);
    CREATE INDEX idx_items_question ON items(question_id);
