apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      code VARCHAR(16) NOT NULL,
      age TEXT,
      gender JSONB,
      role INTEGER,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE surveys (
      id SERIAL PRIMARY KEY,
      title TEXT,
      description TEXT,
      status TEXT,
      public_id TEXT
    );

    CREATE TABLE responses (
      id SERIAL PRIMARY KEY,
      survey_public_id TEXT,
      answers JSONB
    );
