apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      initContainers:
        - name: init-db
          image: postgresql-16:latest
          command:
            - sh
            - -c
            - |
              echo "Init container apenas garantindo arquivos disponíveis"
          volumeMounts:
            - name: init-db
              mountPath: /scripts
      
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-16:latest
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: survey-config
                  key: DB_NAME
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: survey-secret
                  key: DB_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: survey-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data

            - name: init-db
              mountPath: /opt/app-root/src/initdb.d              

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
