apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/
  - database/
  - backend/
  - frontend/
  - openshift/

images:
  - name: survey-api
    newName: image-registry.openshift-image-registry.svc:5000/flaviacb-dev/survey-api
    newTag: latest

  - name: survey-frontend
    newName: image-registry.openshift-image-registry.svc:5000/flaviacb-dev/survey-frontend
    newTag: latest
