apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      
      securityContext:
        runAsUser: 1007550000
        fsGroup: 1007550000

      initContainers:
        - name: copy-config
          image: registry.access.redhat.com/ubi8/ubi-minimal
          command:
            - sh
            - -c
            - |
              mkdir -p /vault/config && \
              cp /config/vault.hcl /vault/config/vault.hcl
          volumeMounts:
            - name: vault-config
              mountPath: /config
            - name: vault-config-writable
              mountPath: /vault/config

      containers:
        - name: vault
          image: registry.connect.redhat.com/hashicorp/vault:1.15.6-ubi
      
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
      
          env:
            - name: SKIP_CHOWN
              value: "true"
      
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"

          ports:
            - containerPort: 8200

          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 10

          volumeMounts:
            - name: vault-config-writable
              mountPath: /vault/config

            - name: vault-data
              mountPath: /vault/data

      volumes:
        - name: vault-config
          configMap:
            name: vault-config

        - name: vault-config-writable
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
