apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault

  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault

      containers:
        - name: vault
          image: registry.connect.redhat.com/hashicorp/vault:latest

          securityContext: {}

          env:
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"

          args:
            - "server"
            - "-config=/vault/config/vault.hcl"

          ports:
            - containerPort: 8200
              name: http

          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"

          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 10

          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true

            - name: vault-data
              mountPath: /vault/data

      volumes:
        - name: vault-config
          configMap:
            name: vault-config

  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
