apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault.hcl: |
    disable_mlock = true

    storage "file" {
      path = "/vault/config"
    }

    listener "tcp" {
      address     = "127.0.0.1:8200"
      tls_disable = true
    }

    api_addr = "http://127.0.0.1:8200"

    ui = true
