apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault

  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault

      containers:
        - name: vault
          image: registry.connect.redhat.com/hashicorp/vault:latest

          securityContext:
            allowHostDirVolumePlugin: true
            allowHostIPC: true
            allowHostNetwork: true
            allowHostPID: true
            allowHostPorts: true
            allowPrivilegedContainer: true
            allowedCapabilities: 
            - '*'
            apiVersion: security.openshift.io/v1
            defaultAddCapabilities: [] 
            fsGroup: 
              type: RunAsAny
            groups: 
            - system:cluster-admins
            - system:nodes
            kind: SecurityContextConstraints
            metadata:
              annotations:
                kubernetes.io/description: 'privileged allows access to all privileged and host
                  features and the ability to run as any user, any group, any fsGroup, and with
                  any SELinux context.  WARNING: this is the most relaxed SCC and should be used
                  only for cluster administration. Grant with caution.'
              creationTimestamp: null
              name: privileged
            priority: null
            readOnlyRootFilesystem: false
            requiredDropCapabilities: null 
            runAsUser: 
              type: RunAsAny
            seLinuxContext: 
              type: RunAsAny
            seccompProfiles:
            - '*'
            supplementalGroups: 
              type: RunAsAny
            users: 
            - system:serviceaccount:default:registry
            - system:serviceaccount:default:router
            - system:serviceaccount:openshift-infra:build-controller
            volumes: 
            - '*'

          env:
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"

          args:
            - "server"
            - "-config=/vault/config/vault.hcl"

          ports:
            - containerPort: 8200
              name: http

          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"

          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 60
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
            initialDelaySeconds: 30
            periodSeconds: 10

          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true

            - name: vault-data
              mountPath: /vault/data

      volumes:
        - name: vault-config
          configMap:
            name: vault-config

  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
