apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: survey-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: survey-secret
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/survey
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/survey
        property: DB_PASSWORD
