apiVersion: v1
kind: Secret
metadata:
  name: survey-secret
type: Opaque
stringData:
  DB_USER: <path:secret/data/survey#DB_USER>
  DB_PASSWORD: <path:secret/data/survey#DB_PASSWORD>
  JWT_SECRET: <path:secret/data/survey#JWT_SECRET>
